from .login import *
from .courses import *
from .authmeta import *
from .user import *
from .create_course import *
from .cousers_list import *
from .password import *
from .video_content import *
from .test_content import *
from .list_courses import *
from .statistical import *
from .master import *
from .managestatistical import *
from .signup import *